fos_rest:
    routing_loader:
        include_format: true
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
    view:
        view_response_listener:
            enabled: true
#    exception:
#        enabled: true
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        rules:
            - { path: ^/album, prefer_extension: true, fallback_format: json, priorities: [ json ] }
