album:
        type: rest
        resource: App\Controller\AlbumController

user:
        type: rest
        resource: App\Controller\UserController

api_login_check:
            path: /api/login_check
